version: "3"
services:
    gateway:
        build:
            dockerfile: ../Docker/gateway.Dockerfile
            context: ./src
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - ENV=production
    proximity:
        build:
            dockerfile: ../Docker/proximity.Dockerfile
            context: ./src
        depends_on:
            - redis
        env_file:
            - .env
        environment:
            - ENV=production
    nginx:
        image: nginx:latest
        depends_on:
            - gateway
        ports:
            - ${PORT}:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        env_file:
            - .env
    redis:
        image: redis:latest

restart: on-failure
