version: "3"
services:
    gateway:
        build:
            dockerfile: ../Docker/gateway.Dockerfile
            context: ./src
        env_file:
            - .env
        environment:
            - ENV=production
    nginx:
        image: nginx:latest
        depends_on:
            - gateway
        ports:
            - 8080:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
